### ISSUE TITLE
How to use Caliper in 2014-08 in reality

### ISSUE THREAD

**Issue by GoogleCodeExporter** [google/caliper#300] opened 2015-05-19 15:33 UTC
```
this is just a copy&paste help for other users
---------------------------------
git clone https://code.google.com/p/caliper/      (due to unreleased beta-2)

mvn install -Dmaven.test.skip=true     (test skip due to unresolved bug)

then use in POM.xml as 

        <dependency>
            <groupId>com.google.caliper</groupId>
            <artifactId>caliper</artifactId>
            <version>1.0-beta-SNAPSHOT</version>
        </dependency>

every developer in your team has to do this    (due to unreleased beta-2)
```

Original issue reported on code.google.com by `max.at.x...@gmail.com` on 6 Aug 2014 at 7:51

**Comment by netdpb** [comment] 2019-09-27 17:23
This is not a bug report or feature request. Closing.

**Closed by netdpb** 2019-09-27 17:23 UTC
Labels: type=defect
